all:
	cd functions; make all; cd ..
	cd posinfoBlock; make all; cd ..
	cd varSizeNodeTree; make all; cd ..
	cd metaDataRestrictions; make all; cd ..
	cd ranker; make all; cd ..
	cd randoc; make all; cd ..
test: all
	cd functions; make test; cd ..
	cd posinfoBlock; make test; cd ..
	cd varSizeNodeTree; make test; cd ..
	cd metaDataRestrictions; make test; cd ..
	cd ranker; make test; cd ..
	cd randoc; make test; cd ..
clean:
	cd functions; make clean; cd ..
	cd posinfoBlock; make clean; cd ..
	cd varSizeNodeTree; make clean; cd ..
	cd metaDataRestrictions; make clean; cd ..
	cd ranker; make clean; cd ..
	cd randoc; make clean; cd ..

