all:
	cd utils; make all; cd ..
	cd randoc; make all; cd ..
	cd program; make all; cd ..
test: all
	cd randoc; make test; cd ..
	cd program; make test; cd ..
clean:
	cd utils; make clean; cd ..
	cd randoc; make clean; cd ..
	cd program; make clean; cd ..

