set(Boost_USE_MULTITHREADED ON)
set( Boost_INCLUDE_DIR /usr/include )
find_package( Boost 1.53.0 COMPONENTS atomic QUIET)
if( Boost_ATOMIC_FOUND )
	find_package( Boost 1.53.0 REQUIRED COMPONENTS thread system date_time atomic)
else()
	find_package( Boost 1.53.0 REQUIRED COMPONENTS thread system date_time)
endif()
