function(CheckHasModule Module)
  find_package(${Module} QUIET)
  if(NOT DEFINED ${Module}_DIR)
    set(HAS_MODULE_${Module} TRUE PARENT_SCOPE)
  elseif(${Module}_DIR)
    set(HAS_MODULE_${Module} TRUE PARENT_SCOPE)
  else()
    set(HAS_MODULE_${Module} FALSE PARENT_SCOPE)
  endif()
endfunction()

CheckHasModule(Intl)
MESSAGE( STATUS  "CMake module for libintl exists: ${HAS_MODULE_Intl}" )
if(HAS_MODULE_Intl)
  find_package(Intl REQUIRED)
  if(FOUND_Intl)
    MESSAGE( STATUS  "libintl found." )
  endif()
  MESSAGE( STATUS "libintl libraries: ${Intl_LIBRARIES}" )
endif()

find_package(Gettext REQUIRED)
